INSERT INTO tasks (name, answer, topic_id, language_id, task_type_id, options) VALUES
('She ___ to school yesterday.', 'went', 1, 1, 1, ARRAY['go', 'went', 'gone', 'going']),
('They ___ football last weekend.', 'played', 1, 1, 1, ARRAY['play', 'played', 'plays', 'playing']),
('He ___ not like coffee.', 'does', 1, 1, 1, ARRAY['do', 'does', 'did', 'doing']),
('We ___ at home now.', 'are', 1, 1, 1, ARRAY['is', 'am', 'are', 'be']),
('I ___ a book every week.', 'read', 1, 1, 1, ARRAY['reads', 'read', 'reading', 'readed']),
('She ___ TV right now.', 'is watching', 1, 1, 1, ARRAY['watch', 'watches', 'is watching', 'watched']),
('They ___ dinner at the moment.', 'are cooking', 1, 1, 1, ARRAY['cook', 'cooks', 'are cooking', 'cooked']),
('He ___ to music now.', 'is listening', 1, 1, 1, ARRAY['listen', 'listens', 'is listening', 'listened']),
('I saw ___ elephant at the zoo.', 'an', 1, 1, 1, ARRAY['a', 'an', 'the', '-']),
('___ sun is very bright today.', 'The', 1, 1, 1, ARRAY['A', 'An', 'The', '-']),
('She wants to be ___ teacher.', 'a', 1, 1, 1, ARRAY['a', 'an', 'the', '-']),
('The cat is ___ the table.', 'on', 1, 1, 1, ARRAY['in', 'on', 'at', 'under']),
('We meet ___ Monday.', 'on', 1, 1, 1, ARRAY['in', 'on', 'at', 'by']),
('She was born ___ 1995.', 'in', 1, 1, 1, ARRAY['in', 'on', 'at', 'by']),
('Choose the synonym for ''happy'':', 'joyful', 2, 1, 1, ARRAY['sad', 'joyful', 'angry', 'tired']),
('Choose the synonym for ''big'':', 'large', 2, 1, 1, ARRAY['small', 'large', 'tiny', 'short']),
('Choose the synonym for ''fast'':', 'quick', 2, 1, 1, ARRAY['slow', 'quick', 'late', 'early']),
('Choose the antonym for ''hot'':', 'cold', 2, 1, 1, ARRAY['cold', 'warm', 'heat', 'fire']),
('Choose the antonym for ''up'':', 'down', 2, 1, 1, ARRAY['up', 'down', 'left', 'right']),
('Choose the antonym for ''start'':', 'finish', 2, 1, 1, ARRAY['start', 'begin', 'finish', 'continue']),
('What does ''ubiquitous'' mean?', 'present everywhere', 2, 1, 1, ARRAY['rare', 'present everywhere', 'expensive', 'ancient']),
('What does ''benevolent'' mean?', 'kind', 2, 1, 1, ARRAY['evil', 'kind', 'angry', 'sad']),
('What does ''ephemeral'' mean?', 'short-lived', 2, 1, 1, ARRAY['permanent', 'short-lived', 'beautiful', 'dangerous']),
('The past tense of ''go'' is ''went''.', 'true', 1, 1, 3, null),
('The article ''an'' is used before consonant sounds.', 'false', 1, 1, 3, null),
('''Happy'' and ''sad'' are synonyms.', 'false', 2, 1, 3, null),
('The plural of ''child'' is ''childs''.', 'false', 1, 1, 3, null),
('''Quickly'' is an adverb.', 'true', 1, 1, 3, null),
('Complete: To be or ___ to be.', 'not', 1, 1, 2, null),
('Complete: All that glitters is ___ gold.', 'not', 2, 1, 2, null),
('Complete: The early bird catches the ___.', 'worm', 2, 1, 2, null),
('Complete: When in Rome, do ___ the Romans do.', 'as', 1, 1, 2, null),
('Complete: Actions speak ___ than words.', 'louder', 2, 1, 2, null);