server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/voxi_db
spring.datasource.username=voxi_user
spring.datasource.password=voxi_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=M9Y8HCk8VWiecC8112KoubkYT6BHBuKZdFESMQF3mnq
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

cookie.access-token-name=access_token
cookie.refresh-token-name=refresh_token
cookie.secure=false
cookie.http-only=true
cookie.same-site=Strict
cookie.path=/
cookie.max-age=604800

logging.level.com.voxi=DEBUG
logging.level.org.springframework.security=DEBUG

spring.application.name=java-service
